# system configuration
system:
  addr: 6000

# captcha configuration
captcha:
  keyLong: 6
  imgWidth: 240
  imgHeight: 80

# jwt configuration
jwt:
  signingkey: zero
  expirestime: 7d
  buffertime: 1d
  issuer: zero