# system configuration
system:
  addr: 6000
  dbtype: mysql

# captcha configuration
captcha:
  keyLong: 6
  imgWidth: 240
  imgHeight: 80

# jwt configuration
jwt:
  signingkey: zero
  expirestime: 7d
  buffertime: 1d
  issuer: zero

# mysql connect configuration
mysql:
  path: "localhost"
  port: "3306"
  config: "parseTime=True"
  dbname: "questionsbank"
  username: "root"
  password: "123456"
  maxidleconns: 10
  maxopenconns: 100
  logmode: ""
  logzap: false